#!/usr/bin/env python3
"""
AndroidGuides.com — Crawlable-HTML generator (P2)

Reads devices.json and writes devices-static.html: one plain-English,
plain-HTML sentence per device. This fragment is what AI crawlers and
non-JavaScript visitors read on /devices (they don't run the JS table,
so without this they'd see an empty page). Runs monthly in the same
GitHub Actions workflow as update_devices.py; the fragment is embedded
in the /devices WordPress page (auto-push arrives with P3).

Usage: python generate_static.py
"""

import json
from datetime import date, datetime
from pathlib import Path

INPUT = Path(__file__).parent / "devices.json"
OUTPUT = Path(__file__).parent / "devices-static.html"

MONTHS = ["January", "February", "March", "April", "May", "June", "July",
          "August", "September", "October", "November", "December"]


def human(iso: str) -> str:
    d = datetime.fromisoformat(iso).date()
    return f"{MONTHS[d.month - 1]} {d.day}, {d.year}"


def esc(s: str) -> str:
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def sentence(d: dict, today: date) -> str:
    name = esc(f"{d['brand']} {d['model']}")
    eol = datetime.fromisoformat(d["eol"]).date()
    verb = "ended on" if eol < today else "are scheduled to end on"
    return (f"<li>Android security updates for the <b>{name}</b> {verb} "
            f"<b>{human(d['eol'])}</b> (released {human(d['released'])}).</li>")


def main() -> int:
    data = json.loads(INPUT.read_text())
    devices = sorted(data["devices"], key=lambda x: x["released"], reverse=True)
    today = date.today()

    n = len(devices)
    brands = {}
    ok = soon = ended = 0
    for d in devices:
        brands[d["brand"]] = brands.get(d["brand"], 0) + 1
        left = (datetime.fromisoformat(d["eol"]).date() - today).days
        if left < 0:
            ended += 1
        elif left <= 365:
            soon += 1
        else:
            ok += 1
    brand_txt = ", ".join(f"{v} {k}" for k, v in sorted(brands.items()))

    items = "\n".join(sentence(d, today) for d in devices)
    html = f"""<!-- devices-static fragment · generated {data['generated']} · {n} devices · auto-generated by generate_static.py — do not hand-edit -->
<section id="agd-static">
  <h2>Android security update end dates — full list</h2>
  <p>As of {human(data['generated'])}, AndroidGuides.com tracks {n} Android devices ({brand_txt}):
  {ok} still receiving security updates, {soon} losing support within 12 months, and {ended} no longer supported.
  Data refreshes monthly from manufacturer commitments and endoflife.date.</p>
  <ul>
{items}
  </ul>
</section>
"""
    OUTPUT.write_text(html)
    print(f"[OK] wrote {OUTPUT} ({n} sentences; {ok} supported / {soon} ending / {ended} ended)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
